### ISSUE TITLE
Expose Unregister of the service outside

### ISSUE THREAD

**Issue by 0rion7st** [PolymerElements/platinum-sw#58]
Currently the registration object have not been exposed outside. 
It would be great to have an option to unregister the service.
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/unregister

**Comment by jeffposnick** [comment]
Is there a specific reason that you'd anticipate needing to unregister the service worker? Unregistering can be useful at times, but I'm not sure how frequently it would come up.

For those who do need to unregister, it's easy enough to do so directly via `navigator.serviceWorker.ready.then(function(registration) {registration.unregister()});`

**Comment by 0rion7st** [comment]
Two reasons for that:
1. In cases as mine when custom browser used (CEF3 in my case) I had issues with zombie process when the browser is down. Something hasn't been properly addressed poorly in CEF3.2378.1268 and below. 
2. Registration object good to have outside in any case. I had great experience with iron-ajax and iron-request which expose xhr object outside. Expected the same approach in this element.

**Comment by jeffposnick** [comment]
The `XMLHttpRequest` object associated with `<iron-ajax>` is specific to a given instance of `<iron-ajax>`, and if it wasn't exposed it wouldn't otherwise be available outside the `<iron-ajax>` scope.

The service worker registration is globally available via the `navigator.serviceWorker.ready` promise, and if you do need to unregister the service worker then I'd just recommend using that as explained in my previous comment.
