### ISSUE TITLE
Add property for Online/Offline state

### ISSUE THREAD

**Issue by mbergeron** [PolymerElements/platinum-sw#72]
Hi,

I don't know if this should fall under the platinum-sw project, but it would be nice to get information about the online/offline state of the application.

This could be use to warn the user about being in "Online" or "Offline" mode and could also be use to trigger other functions within the app.

An event that would trigger on the state change would also be very helpful.

**Comment by jeffposnick** [comment]
You can use https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine directly. 

I don't think that wrapping that underlying API is within scope for the `<platinum-sw>` element set, since you would normally not need to take special actions within the elements to account for whether the browser has a connection or not. And the underlying API is independent from service workers.
