### ISSUE TITLE
navigateFallback

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/platinum-sw#86]
How to setup `navigateFallback` URL?

https://github.com/GoogleChrome/sw-precache#navigatefallback-string

**Comment by jeffposnick** [comment]
Apologies for the confusion.

`<platinum-sw>` is a wrapper for the [`sw-toolbox`](https://github.com/GoogleChrome/sw-toolbox) library, which is not the same thing as the [`sw-precache`](https://github.com/GoogleChrome/sw-precache) library. `navigateFallback` is only part of the `sw-precache` library.

You can use `sw-precache` with a Polymer-based application, but since it's a build-time integration, there's no wrapper Polymer element. You just include `sw-precache` as part of your build process.

**Comment by aletorrado** [comment]
Since `platinum-sw` provides precache functionality anyway, it would be nice to replicate this kind of custom fetch for navigation events. Do you think it possible?
